# Generated by Django 2.1.5 on 2019-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_1', models.CharField(max_length=30)),
                ('lesson_2', models.CharField(max_length=30)),
                ('lesson_3', models.CharField(max_length=30)),
                ('lesson_4', models.CharField(max_length=30)),
                ('lesson_5', models.CharField(max_length=30)),
                ('lesson_6', models.CharField(max_length=30)),
                ('lesson_7', models.CharField(max_length=30)),
                ('lesson_8', models.CharField(max_length=30)),
            ],
        ),
    ]
